-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 22, 2023 at 01:33 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `jaspa`
--

-- --------------------------------------------------------

--
-- Table structure for table `animais`
--

CREATE TABLE `animais` (
  `id` int(11) NOT NULL,
  `nome` text NOT NULL,
  `foto` text NOT NULL,
  `ameaca` text NOT NULL,
  `info` text NOT NULL,
  `situacao` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `animais`
--

INSERT INTO `animais` (`id`, `nome`, `foto`, `ameaca`, `info`, `situacao`) VALUES
(1, 'Onça Pintada', 'uploads\\onca-pintada.jpg', 'Perda de habitat e caça', '<strong>Quem é?:</strong> A Onça-Pintada, também chamada de Jaguar, é o maior felino das Américas e o terceiro maior do mundo, depois dos tigres e dos leões. Seu nome científico é Panthera onca1. Ela é um animal predador, carnívoro e vertebrado (possui vértebras), pertencente à ordem carnívora e à família felidae.\r\n<br><br>\r\n<strong>Ameaças:</strong> A onça-pintada é um animal ameaçado de extinção no Brasil. As principais causas são a caça ilegal e o aumento do desmatamento e queimadas. Outras ameaças incluem a perda e fragmentação de habitat associadas principalmente à expansão agrícola, mineração, implantação de hidrelétricas, ampliação da malha viária e a eliminação de indivíduos por caça ou retaliação por predação de animais domésticos.\r\n<br><br>\r\n<strong>Habitat:</strong> As onças-pintadas vivem geralmente em densas florestas. Estão espalhadas na América do Norte, Central e Sul1. Elas preferem habitats úmidos de planície, savanas pantanosas ou florestas tropicais.\r\n<br><br>\r\n<strong>Hábitos:</strong> As onças-pintadas, como todos os felinos, são animais noturnos. Ou seja, elas caçam durante à noite. Portanto, dormem durante o dia perto dos rios ou nas árvores. Vale citar que são ótimas nadadoras e durante muito tempo ficam na água1. Elas também apresentam hábitos solitários.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> A onça-pintada possui um corpo musculoso e robusto, com membros curtos e fortes5. Sua estrutura corporal é adaptada para dar grandes saltos, facilitando a caça de suas presas. Ela possui dentes fortes e afiados para triturar seus alimentos crus, além de mandíbulas alongadas e muito fortes.\r\n<br><br>\r\n<strong>Dieta:</strong> A onça-pintada é um animal carnívoro e, portanto, se alimenta predominantemente da carne de outros animais menores ou menos ágeis que ela. Por exemplo, veados, capivaras, macacos, antas, tatus, tamanduás, jacarés, cobras, peixes, porco-selvagem e diversas aves.', 1),
(2, 'Mico-Leão-Dourado', 'uploads\\mico-leao-dourado.jpg', 'Perda de habitat', '<strong>Quem é?:</strong> O Mico-leão-dourado (Leontopithecus rosalia) é um mamífero endêmico da Mata Atlântica brasileira, especificamente na região do Rio de Janeiro. Ele é conhecido por sua pelagem dourada a alaranjada e uma juba muito característica, que lhe conferiu o nome popular.\r\n<br><br>\r\n<strong>Ameaças:</strong> O Mico-leão-dourado está ameaçado de extinção devido a várias razões. A principal ameaça é a destruição do seu habitat natural, a Mata Atlântica, devido à urbanização desenfreada, ao avanço da agricultura e à fragmentação das florestas. Além disso, a caça ilegal e o comércio ilegal de animais também contribuem para a ameaça de extinção do mico-leão-dourado.\r\n<br><br>\r\n<strong>Habitat:</strong> O Mico-leão-dourado é endêmico da Mata Atlântica, ou seja, é encontrado exclusivamente nesse bioma. Originalmente, era distribuído do Rio de Janeiro até o Espírito Santo. Hoje, eles são encontrados em fragmentos florestais na Bacia do Rio São João, localizados em alguns municípios do Rio de Janeiro.\r\n<br><br>\r\n<strong>Hábitos:</strong> O Mico-leão-dourado possui hábitos diurnos. Eles vivem em grupos de 2 a 8 indivíduos, liderados por um casal reprodutor. Eles são rápidos, acrobáticos e analíticos, usando suas garras afiadas e curvadas nos dedos dos pés para agarrar troncos e ramos de árvores.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Mico-leão-dourado tem pelos em tons de vermelho-dourado, longos braços, dedos longos e com garras nas mãos. Suas fortes pernas e longa cauda permitem uma locomoção ágil e acrobática em todos os substratos da floresta. Eles têm entre 20 e 36 cm de comprimento, isso sem incluir a cauda. Esses animais pesam menos de 900 gramas.\r\n<br><br>\r\n<strong>Dieta:</strong> A dieta do Mico-leão-dourado é essencialmente frugívora, ou seja, baseada principalmente em frutas. Cerca de 70% da sua alimentação consiste de frutos diversos, como mangas, cajus, goiabas e bananas. Além disso, também consome néctar, flores, folhas jovens, insetos e pequenos vertebrados, como lagartos e pequenos pássaros.', 1),
(3, 'Arara-azul', 'uploads\\arara-azul.jpg', 'Caça e comércio ilegal', '<strong>Quem é?:</strong> A Arara-azul, também conhecida como arara-azul-grande, é uma ave pertencente à espécie Anodorhynchus hyacinthinus. Ela possui uma coloração predominantemente azul-cobalto, com regiões em amarelo ao redor dos olhos e na mandíbula inferior. Essa é uma ave de grande porte com cerca de 1,0 m de comprimento da cabeça à cauda e 1,20 m de envergadura, pesando, aproximadamente, 1,3 kg1. \r\n<br><br>\r\n<strong>Ameaças:</strong> A Arara-azul está atualmente ameaçada de extinção devido à caça, ao comércio clandestino e à degradação em seu habitat natural por conta do desmatamento. Além disso, a destruição do habitat é um problema grave, pois são nesses ambientes que as araras-azuis conseguem seu alimento e local adequado para a reprodução.\r\n<br><br>\r\n<strong>Habitat:</strong> A Arara-azul habita as regiões tropicais, em especial, regiões abertas do Brasil, Paraguai e Bolívia. No Brasil, embora sua população esteja bastante reduzida, são encontradas em diversos biomas, principalmente no Pantanal, onde elas ocupam áreas afetadas pelo homem, assim como bordas de cordilheiras.\r\n<br><br>\r\n<strong>Hábitos:</strong> As Araras-azuis são animais muito sociáveis. Elas gostam de voar em pares ou em grupo. Nos fins de tarde, se reúnem em bandos em árvores “dormitório”. Além disso, os casais são fiéis e dividem as tarefas de cuidar dos filhotes.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> A Arara-azul possui o bico adaptado para a alimentação, geralmente composta de sementes, frutas e nozes. Estas aves costumam ser encontradas em florestas tropicais e no Brasil estão presentes principalmente no Pantanal, na Floresta Amazônica e na região da Mata Atlântica1. Ela tem uma envergadura impressionante, que chega até cerca de 1,10 metros de uma ponta até a outra, tornando-se a arara mais “larga” do mundo.<br><br>\r\n<strong>Dieta:</strong> A dieta de uma arara-azul consiste em frutas, sementes, insetos, frutos secos, pequenos répteis e até mesmo peixes. Frutas são a base de sua dieta e incluem bananas, goiabas, manga, abacaxi e outras frutas tropicais. As sementes e frutos secos incluem sementes de palmeiras, castanhas, nozes e sementes de girassol.', 1),
(4, 'Porco Caruncho', 'uploads\\porcocaruncho.jpg', '', '', 0),
(5, 'Avoante', 'uploads\\avoante.jpg', '', '', 0),
(6, 'São Bernardo', 'uploads\\saobernardo.jpg', '', '', 0),
(7, 'Tilápia', 'uploads\\tilapia.jpg', '', '', 0),
(8, 'Vaca malhada', 'uploads\\vaca.jpg', '', '', 0),
(10, 'Tatu-bola', 'uploads\\tatu-bola.jpg', 'Perda de habitat e caça', '<strong>Quem é?:</strong> O tatu-bola, também conhecido como tatu-apara, bola, bolinha, tranquinha ou tatu-bola-do-nordeste, é a menor e menos conhecida espécie de tatu do Brasil. Seu nome científico é Tolypeutes matacus.\r\n<br><br>\r\n<strong>Ameaças:</strong> Infelizmente, o tatu-bola-da-caatinga encontra-se sob risco de extinção, apresentando o estado de conservação vulnerável. Entre as principais causas, podemos citar a destruição de seu habitat e a caça predatória. Nos últimos dez anos a população de tatus-bolas diminuiu cerca de 30%.\r\n<br><br>\r\n<strong>Habitat:</strong> O tatu-bola habita a caatinga da região nordeste do Brasil (estados de Pernambuco, Ceará, Alagoas, Bahia, Sergipe e Piauí). São encontrados também em outros países como, por exemplo, Paraguai, Estados Unidos, Argentina e Bolívia.\r\n<br><br>\r\n<strong>Hábitos:</strong> O tatu-bola possui hábito de vida mais noturno do que diurno. Eles não cavam tocas, mas habitam buracos feitos por outros animais e podem se cobrir com folhas. No cerrado, têm hábitos diurnos e noturnos, com dois picos de atividade: entre às 14 e 18h e entre às 20h e 23h.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O tatu-bola é um animal onívoro, que apresenta corpo com uma casca rígida e mede em torno de 25 cm. Essa armadura funciona muito bem para a sua proteção. São muito conhecidos no Brasil, e é praticamente a única espécie capaz de rolar em formato de bola, por isso o nome atribuído. Comprimento (adulto): entre 40 e 50 cm (entre a cabeça e a cauda). Peso (adulto): entre 1,3 e 1,8 quilo.\r\n<br><br>\r\n<strong>Dieta:</strong> A alimentação do tatu-bola é composta por formigas, larvas de insetos, raízes, aranhas, ovos e frutas.', 1),
(11, 'Ouriço-preto', 'uploads\\ourico-preto.jpg', 'Perda de habitat', '<strong>Quem é?:</strong> O ouriço-preto, também conhecido como luís-cacheiro-preto, é uma espécie de roedor da família dos eretizontídeos (Erethizontidae). Ele é endêmico da porção central da Mata Atlântica, do sul do estado de Sergipe, Bahia, Espírito Santo até o norte do Rio de Janeiro1. Ele é a espécie mais antiga da família Erethizontidae.\r\n<br><br>\r\n<strong>Ameaças:</strong> O ouriço-preto é categorizado como espécie vulnerável à extinção na Lista Vermelha da União Internacional para a Conservação da Natureza (UICN / IUCN), na Portaria MMA N.º 444 de 17 de dezembro de 2014 e no Livro Vermelho da Fauna Brasileira Ameaçada de Extinção do Instituto Chico Mendes de Conservação da Biodiversidade (ICMBio). A principal ameaça à espécie é a perda de habitat ocorrida no bioma da Mata Atlântica.\r\n<br><br>\r\n<strong>Habitat:</strong> O ouriço-preto habita as matas do leste do Brasil, em estados como o Piauí, Sergipe, Bahia, Espírito Santo e Rio de Janeiro. Sua distribuição geográfica abrange as florestas da porção central da Mata Atlântica, desde o extremo norte do estado do Rio de Janeiro até o sul de Sergipe, incluindo os estados do Espírito Santo, Bahia e nordeste de Minas Gerais. <br><br>\r\n<strong>Hábitos:</strong> O ouriço-preto é um animal noturno e solitário. Ele tem hábito estritamente arborícola, gastando quase todo o seu tempo em cima de árvores e lianas. Ele possui diversas adaptações para o hábito arborícola: cauda preênsil, fortes garras e, ao invés do hálux, apresenta uma grande calosidade móvel e preensora provida de uma estrutura óssea que alarga bastante a sola das patas.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O ouriço-preto possui espinhos por todo o corpo, principalmente na região do dorso, com cauda curta quase nula. Os machos podem chegar a pesar mais de 2 quilos e medir cerca de 69 cm de comprimento, já as fêmeas são sempre menores e até possuem uma coloração mais clara, em cinza-escuro.\r\n<br><br>\r\n<strong>Dieta:</strong> O ouriço-preto é um animal omnívoro, o que significa que se alimenta de uma variedade de alimentos, mas sua dieta é predominantemente vegetariana. Uma parte significativa de sua alimentação consiste em frutas, como maçãs, peras, uvas, morangos e outras frutas silvestres disponíveis em seu ambiente. Além das frutas, esses pequenos mamíferos também se alimentam de insetos, como formigas, besouros e larvas.', 1),
(12, 'Guaruba', 'uploads\\guaruba.jpg', '', '', 0),
(13, 'Peixe-boi', 'uploads\\peixe-boi.jpg', 'Caça', '<strong>Quem é?</strong> O peixe-boi-da-Amazônia (nome científico: Trichechus inunguis) é a menor espécie de peixe-boi do mundo, habitando exclusivamente rios e lagos de água doce na bacia Amazônica. Seu couro é extremamente grosso e resistente, e sua coloração varia de cinza a preto, com uma mancha específica de cor branca ou rosada na barriga, semelhante a uma impressão digital. Ele pode atingir até 3 metros de comprimento e pesar até 450 quilos.\r\n<br><br>\r\n<strong>Ameaças:</strong> Apesar de ser classificado como vulnerável, o peixe-boi-da-Amazônia enfrenta desafios significativos. Sua população declinou consideravelmente no último século devido à caça por sua carne, gordura e pele. Durante o período colonial, entre 1935 e 1954, entre 80 mil e 140 mil peixes-bois-da-Amazônia foram mortos para esses fins. Embora essa prática tenha se tornado mais rara, a espécie ainda sofre com a perda de habitat, poluição e captura acidental em redes de pesca.\r\n<br><br>\r\n<strong>Habitat:</strong> O peixe-boi-da-Amazônia é encontrado em grande parte dos rios da bacia Amazônica, mas não ocorre acima de regiões com corredeiras. Durante a cheia, prefere várzeas e áreas alagadas com águas superiores a 23°C. Na seca, migra para lagos e canais profundos. Sua dieta consiste em plantas aquáticas e semiaquáticas, com cerca de 50 espécies diferentes identificadas em seu cardápio. A espécie é predominantemente solitária, embora já tenha sido avistada em grupos, geralmente composto por uma mãe e seu filhote. A gestação dura 12 meses, e apenas um pequeno peixe-boi nasce de cada vez. As glândulas mamárias estão localizadas nas axilas do animal.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O peixe-boi-da-Amazônia possui uma coloração cinza escura, um corpo robusto e uma cauda comprida e arredondada. Diferentemente de outros peixes-bois, ele não tem unhas na ponta das nadadeiras.\r\n<br><br>\r\n<strong>Dieta:</strong> Como herbívoro, o peixe-boi-da-Amazônia consome plantas aquáticas e semiaquáticas, desempenhando um papel importante na dispersão de sementes de frutos do cerrado, como a lobeira (Solanum lycocarpum).\r\n', 1),
(14, 'Salsichinha', 'uploads\\salsichinha.jpg', '', '', 0),
(15, 'Boto-cor-de-rosa', 'uploads\\boto-cor-de-rosa.jpg', 'Caça e poluição', '<strong>Quem é?</strong> O Boto-cor-de-rosa, também conhecido como Inia geoffrensis, é um mamífero aquático que vive em rios da América do Sul, incluindo Brasil, Bolívia, Colômbia, Equador, Peru e Venezuela. Ele é o maior golfinho de água doce do mundo e é conhecido por sua coloração rosa-avermelhada na região ventral dos machos.\r\n<br><br>\r\n<strong>Ameaças:</strong> O Boto-cor-de-rosa está ameaçado de extinção devido a várias atividades humanas, como a construção de hidrelétricas, a matança para serem usados como iscas para a pesca da espécie piracatinga, a exploração do petróleo, a circulação de barcos e turistas, a poluição das águas e a contaminação por mercúrio.\r\n<br><br>\r\n<strong>Habitat:</strong> O Boto-cor-de-rosa é encontrado em rios principais e cachoeiras da região amazônica, em águas calmas e pouco profundas, em regiões de várzea (florestas alagadas sazonais).\r\n<br><br>\r\n<strong>Hábitos:</strong> O Boto-cor-de-rosa é um animal solitário e apresenta display sócio-sexual, quando machos adultos utilizam galhos e outros objetos para cortejar a fêmea. Tudo indica que é um comportamento relacionado à reprodução. Eles possuem uma habilidade conhecida como biossonar, que os torna capazes de identificar objetos e a qual distância e forma eles se encontram.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Boto-cor-de-rosa é um animal que faz parte da mesma família que as baleias e que os golfinhos, porém a maior diferença entre eles é o fato do boto viver nas águas doces e não nos mares de águas salgadas. Os botos machos são considerados um pouco maiores que as fêmeas, eles conseguem medir até 2,5 metros e a pesar até 200 quilos, enquanto as fêmeas medem no máximo 2,2 metros e podem pesar até 150 quilos. Eles possuem corpos bastante flexíveis, o que é muito bom e facilita na hora em que eles precisam caçar suas presas ou quando precisam desviar de obstáculos que pode haver no meio de seu caminho.\r\n<br><br>\r\n<strong>Dieta:</strong> A base alimentar do Boto-cor-de-rosa é formada por muitas espécies diferentes de peixes, mas eles também podem se alimentar de crustáceos e de moluscos.', 1),
(16, 'Muriqui-do-sul', 'uploads\\muriqui-do-sul.jpg', 'Perda de habitat e caça', '<strong>Quem é?:</strong> O Muriqui-do-sul (nome científico: Brachyteles arachnoides), também chamado simplesmente de mono-carvoeiro ou muriqui, é uma espécie de primata da família Atelidae e do gênero Brachyteles endêmico da Mata Atlântica brasileira.\r\n<br><br>\r\n<strong>Ameaças:</strong> O Muriqui-do-Sul está criticamente ameaçado de extinção. Isso se deve principalmente à alta fragmentação da Mata Atlântica e à caça ilegal, que pode levar pequenas populações reduzidas à extinção rapidamente. Restam pouco mais de 1.200 indivíduos e sua população segue em declínio.\r\n<br><br>\r\n<strong>Habitat:</strong> É nativo do Brasil e ocorre apenas na Serra do Mar entre o norte do Paraná, São Paulo, Rio de Janeiro e um pequeno trecho de Minas Gerais. Ele habita sobretudo a floresta da Mata Atlântica.\r\n<br><br>\r\n<strong>Hábitos:</strong> De hábitos diurnos, os muriquis geralmente vivem em altitudes que variam de 400 m a até 2.050 m de altitude. É um animal dócil, de pelagem bege espessa e macia, com anel de pelos mais claros ao redor da face. Além de ser sociável e dócil, gosta de dar abraços.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> Com quase 1,60 m de comprimento e pesando até 15 kg, o muriqui do sul é o maior primata não-humano das Américas1. Os muriquis machos medem entre 55-78 cm de comprimento — sem contar com a cauda, que acrescenta mais 74-80 cm no comprimento — e podem pesar de 9,6 a 15 kg quando adultos.\r\n<br><br>\r\n<strong>Dieta:</strong> Alimentam-se sobretudo de folhas, mas também podem consumir quantidades significativas de frutas, flores, cascas, bambus, samambaias, néctar, pólen, e sementes.', 1),
(17, 'Mutum-do-sudeste', 'uploads\\mutum-do-sudeste.jpg', 'Desmatamento e caça', '<strong>Quem é?:</strong> O Mutum-do-sudeste, também conhecido como mutum-de-bico-vermelho, é uma espécie de ave galiforme da família dos cracídeos. Seu nome científico é Crax blumenbachii.\r\n<br><br>\r\n<strong>Ameaças:</strong> Esta espécie está ameaçada de extinção. Sua população está diminuindo devido à caça e ao desmatamento. Em 2020, foi estimado que existiam apenas 250 indivíduos adultos na natureza.\r\n<br><br>\r\n<strong>Habitat:</strong> O Mutum-do-sudeste é endêmico da Mata Atlântica brasileira, sendo encontrado em apenas poucos locais da Bahia e do Espírito Santo.\r\n<br><br>\r\n<strong>Hábitos:</strong> É uma ave que vive principalmente no solo. Diante de sua dificuldade de voar e por preferir o solo, foi comparada com a galinha. Alimenta-se de sementes, frutos, gomos e pequenos invertebrados.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> É uma ave de grande porte, com 82–92 centímetros de comprimento e peso de cerca de 3,5 quilos. O macho tem a parte superior totalmente preta com uma grande crista preta e a parte inferior da barriga branca. A fêmea não tem barbatanas e tem partes superiores pretas, uma crista com barras pretas e brancas, asas marrom-avermelhadas com barras e manchas pretas, com as partes inferiores sendo marrom-avermelhadas ou ocre.\r\n<br><br>\r\n<strong>Dieta:</strong> O Mutum-do-sudeste se alimenta de sementes, frutos, gomos e pequenos invertebrados.', 1),
(18, 'Caranguejo-amarelo', 'uploads\\caranguejo-amarelo.jpg', 'Introdução de espécies exóticas', '<strong>Quem é?:</strong> O Caranguejo-amarelo (Johngarthia lagostoma, syn. Gecarcinus lagostoma) é um caranguejo da família dos gecarcinídeos, também conhecido como caranguejo-ladrão.\r\n\r\n<strong>Ameaças:</strong> O Caranguejo-amarelo está ameaçado de extinção pela destruição de seus habitats, pelo turismo e por outras ameaças antrópicas, como introdução de espécie exóticas em Fernando de Noronha e Trindade. A principal ameaça estar relacionada a introdução de espécie exóticas, por incremento da agricultura e da urbanização.\r\n\r\n<strong>Habitat:</strong> O Caranguejo-amarelo é encontrado principalmente nas ilhas brasileiras de Trindade, Fernando de Noronha e Ascensão.\r\n\r\n<strong>Hábitos:</strong> Este tipo de caranguejo tem hábitos noturnos, quando adultos são terrestres, porém com desenvolvimento larval marinho, apresentam polimorfismo, com padrão de cor que variam do amarelo ao roxo.\r\n\r\n<strong>Estrutura Corporal:</strong> O Caranguejo-amarelo possui carapaça amarela e patas alaranjadas. Este animal, cuja primeira evidência de vida data do período jurássico e que possui milhares de espécies descobertas, dispõe uma série de características bem únicas e que fazem deles seres bastante curiosos.\r\n\r\n<strong>Dieta:</strong> O Caranguejo-amarelo atua como um importante predador de filhotes de tartarugas marinhas.', 1),
(19, 'Soldadinho-do-araripe ', 'uploads\\soldadinho-do-araripe.jpg', 'Perda de habitat', '<strong>Quem é?:</strong> O Soldadinho-do-araripe é uma ave típica da região da Serra do Araripe, principalmente no estado do Ceará, Brasil. É conhecido popularmente como galo-da-mata e língua-de-tamanduá.\r\n<br><br>\r\n<strong>Ameaças:</strong> A principal ameaça de extinção desta espécie é a ocupação humana em áreas de florestas na Chapada do Araripe, levando à redução da vegetação. Infelizmente, o Soldadinho do Araripe encontra-se em estado de perigo crítico de extinção.\r\n<br><br>\r\n<strong>Habitat:</strong> O habitat desta espécie animal é formado por florestas e matas úmidas, próximas às margens de rios e lagos.\r\n<br><br>\r\n<strong>Hábitos:</strong> O Soldadinho do Araripe apresenta hábito de vida diurno, quando costuma voar em busca de alimento e água. Os machos realizam voos de exibição e mostram suas cristas vermelhas para atrair as fêmeas durante a época de acasalamento.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O pássaro adulto pesa cerca de 20 gramas e possui cerca de 15 centímetros de comprimento. Uma das principais características desta ave é a diferença de cor entre machos e fêmeas. Os machos adultos são coloridos (preto, branco e vermelho na cabeça), enquanto as fêmeas são verdes.\r\n<br><br>\r\n<strong>Dieta:</strong> O Soldadinho do Araripe se alimenta, principalmente, de insetos e frutas.', 1),
(20, 'Chororó-de-goiás', 'uploads\\chororó-de-goiás.jpg', 'Perda de habitat', '<strong>Quem é?:</strong> O Chororó-de-goiás (Cercomacra ferdinandi) é uma espécie de ave da família Thamnophilidae. Essas aves são comparativamente mansas e facilmente atraídas por playback.\r\n<br><br>\r\n<strong>Ameaças:</strong> A espécie está ameaçada pela perda e degradação de seu habitat. É considerada uma espécie vulnerável.\r\n<br><br>\r\n<strong>Habitat:</strong> O Chororó-de-goiás é endêmico do Brasil, encontrado do Goiás ao Pará, no vale do rio Araguaia. Seus habitats naturais são: florestas subtropicais ou tropicais úmidas de baixa altitude e matagal úmido tropical ou subtropical.\r\n<br><br>\r\n<strong>Hábitos:</strong> Apresenta forte dimorfismo sexual e é comumente visto aos pares ou em grupos familiares, em áreas sujeitas a inundações onde crescem cipoais densos entre árvores e arbustos. Em geral, move-se nessas brenhas a alturas de 2 a 5 m, logo abaixo do “teto” formado pelos cipós, procurando insetos.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> Os machos são pretos com barras brancas nas asas e branco nas pontas da cauda, enquanto as fêmeas são semelhantes, porém são cinzas com o peito levemente estriado.\r\n<br><br>\r\n<strong>Dieta:</strong> O Chororó-de-goiás se alimenta procurando insetos.', 1),
(21, 'Guariba-de-mãos ruivas', 'uploads\\guariba-de-mãos-ruivas.jpg', 'Perda de habitat', '<strong>Quem é?:</strong> O Guariba-de-mãos-ruivas é uma espécie de macaco exclusivamente brasileiro, conhecido cientificamente como Alouatta belzebul. Ele é endêmico do Brasil, e possui distribuição geográfica disjunta, ocorrendo duas populações separadas: uma na Amazônia e outra na Mata Atlântica do litoral do Nordeste Brasileiro.\r\n<br><br>\r\n<strong>Ameaças:</strong> Infelizmente, o Guariba-de-mãos-ruivas é considerado uma espécie ameaçada de extinção, com populações diminuindo drasticamente em algumas regiões locais de habitat pelo Brasil.\r\n<br><br>\r\n<strong>Habitat:</strong> O Guariba-de-mãos-ruivas vive no norte e leste do Brasil, onde coloniza as áreas da floresta amazônica e semidecídua. Ele pode ser visto em áreas do bioma amazônico e na mata atlântica, circulando em estados diversos do território brasileiro como Alagoas, Amapá, Paraíba, Pará, Rio Grande do Norte, Mato Grosso, Pernambuco e Maranhão, para citar apenas alguns.\r\n<br><br>\r\n<strong>Hábitos:</strong> O Guariba-de-mãos-ruivas é um animal arbóreo, ou seja, passa a maior parte do tempo nas árvores.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Guariba-de-mãos-ruivas tem cabelo geralmente preto, mais esparso na cabeça e no rosto, nu, mas com barba espessa, mais abundante nos machos. Somente na subespécie descolorida as mãos são de cor avermelhada, como indicado pelo nome comum. Também a ponta da cauda pode ser avermelhada. Ele tem uma cauda preênsil um pouco mais longa que o corpo, cuja ponta tem uma parte inferior glabra e é muito sensível: é usada como quinto membro nos movimentos entre as árvores.\r\n<br><br>\r\n<strong>Dieta:</strong> O Guariba-de-mãos-ruivas se alimenta basicamente de folhas e frutos disponíveis na floresta, com dieta altamente rica em fibras.', 1),
(22, 'Cuxiu-preto', 'uploads\\cuxiu-preto.jpg', 'Perda de habitat e caça', '<strong>Quem é?:</strong> O Cuxiú-preto (Chiropotes satanas) é uma espécie de primata endêmica do Brasil.\r\n<br><br>\r\n<strong>Ameaças:</strong> O Cuxiú-preto está criticamente ameaçado por diversos fatores, principalmente a destruição do seu habitat. Nas últimas décadas, a urbanização trouxe a destruição e degradação do seu habitat e até a caça. A fragmentação do habitat está aumentando à medida que as estradas secundárias aumentam e as pessoas se mudam para mais perto das florestas. Junto com o influxo de pessoas, a quantidade de agricultura necessária para sustentar a área aumenta, aumenta a pressão pelo desmatamento. A caça visa a sua carne e suas caudas são usadas como espanadores de poeira.\r\n<br><br>\r\n<strong>Habitat:</strong> O Cuxiú-preto é endêmico do Brasil, ocorrendo desde a margem direita do rio Tocantins, no Pará, até os limites orientais da Amazônia, no Maranhão.\r\n<br><br>\r\n<strong>Hábitos:</strong> Eles são animais bastante sociais, frequentemente se catando e brincando uns com os outros, até mesmo com os de outras espécies. Podem ser encontrados em grupos de cerca de 30 indivíduos. Quando filhotes, os macacos podem ser vistos usando a cauda para agarrar coisas, mas perdem a habilidade conforme o primata fica mais velho.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Cuxiú-preto pode ser identificado por seu cabelo preto espesso e barba característica, além de uma cauda espessa como a de uma raposa. Eles podem ter alguns reflexos marrons amarelados nas costas e nos ombros. Os machos tendem a ser ligeiramente maiores que as fêmeas e também têm uma testa saliente. O corpo mede entre 33,5 e 42,5 cm, com os machos sendo ligeiramente maiores do que as fêmeas. Podem pesar até 3,0 kg e a cauda não é preênsil, medindo de 35,5 a 42 cm.\r\n<br><br>\r\n<strong>Dieta:</strong> O Cuxiú passa a maior parte do tempo procurando frutas e sementes, bem como insetos. Eles usam seus fortes dentes caninos para quebrar cascas duras de frutas e nozes, permitindo-lhes acessar as sementes jovens não maduras dos frutos.', 1),
(23, 'Tubarão-martelo', 'uploads\\tubarao-martelo.jpg', 'Perda de habitat e poluição', '<strong>Quem é?:</strong> O tubarão-martelo (Sphyrna spp.) é um gênero de tubarão, característico pelas projeções existentes em ambos os lados da cabeça, onde se localizam os olhos e as narinas.\r\n<br><br>\r\n<strong>Ameaças:</strong> A degradação do habitat devido ao desenvolvimento e à poluição são ameaças às populações de tubarões-martelo, uma vez que as águas costeiras estão próximas à costa e são mais acessíveis às pessoas. A mudança climática é uma ameaça crescente que impacta o oceano, alterando as áreas de habitat dos tubarões e de suas presas.\r\n<br><br>\r\n<strong>Habitat:</strong> O tubarão-martelo é um espécime que podemos encontrar tanto em águas tropicais como em outros climas temperados.\r\n<br><br>\r\n<strong>Hábitos:</strong> São animais gregários que se deslocam em cardumes que podem atingir 100 exemplares. Eles também são conhecidos por andar em grandes quantidades durante o dia, em grupos que podem chegar a até 100 integrantes.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> As espécies conhecidas de tubarão-martelo têm um comprimento entre 0,9 e 6 metros. Todas as espécies têm duas projeções, uma de cada lado da cabeça, dando a esta o aspecto de um martelo, de onde vem o nome popular da espécie.\r\n<br><br>\r\n<strong>Dieta:</strong> O tubarão-martelo é um predador que consome peixes, cefalópodes, raias e outros tubarões.', 1),
(24, 'Ariranha', 'uploads\\ariranha.jpg', 'Perda de habitat e caça', '<strong>Quem é?:</strong> A Ariranha, também conhecida como onça d\'água e lontra-gigante, é um mamífero carnívoro endêmico da América do Sul. Ela pertence à família Mustelidae, que inclui animais como lontras, texugos e doninhas. Seu nome científico é Pteronura brasiliensis.\r\n<br><br>\r\n<strong>Ameaças:</strong> A Ariranha atualmente se encontra em um estado preocupante de ameaça de extinção, principalmente por conta da ação de seres humanos. As principais ameaças a essa espécie são a caça, a captura para venda como animal de estimação, a degradação e fragmentação ambiental, geradas pela contaminação dos corpos d\'água, e os impactos das construções de barragens, em especial, os empreendimentos hidroelétricos. Além disso, a destruição de habitats e a contaminação da água dos rios por agrotóxicos e metais pesados oriundos do garimpo, como o mercúrio, também são ameaças significativas.\r\n<br><br>\r\n<strong>Habitat:</strong> As Ariranhas são animais semiaquáticos que habitam regiões úmidas como as margens dos rios, lagos e pântanos. Elas são encontradas em diversas partes do Brasil, sendo comum nos rios da Amazônia e do Pantanal. Habitam também diversos países vizinhos: Peru, Equador, Colômbia, Bolívia, Venezuela, Guiana, Suriname e Guiana Francesa.\r\n<br><br>\r\n<strong>Hábitos:</strong> As Ariranhas são animais predadores, diurnos, curiosos, barulhentos e brincalhões. Vivem em bandos (de até dez) e passam o dia se socializando nas margens dos rios, descansando e caçando. São ótimos nadadores e mergulhadores. Elas costumam fazer tocas debaixo das raízes das árvores que estão próximas das margens dos rios, com o intuito de se abrigarem durante a noite. Ali, marcam seus territórios com urina e fezes.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> As Ariranhas possuem um corpo alongado. Sua cabeça é ovalada, os olhos são grandes e as orelhas pequenas. Em relação ao tamanho das ariranhas, vale lembrar que elas podem medir até 1,80 metros de comprimento, sendo que 65 cm são da cauda. Pesam cerca de 35 Kg e os machos costumam ser maiores e mais pesados que as fêmeas. As ariranhas possuem pelos espessos, curtos, de coloração castanha e algumas manchas esbranquiçadas na região do pescoço. A cauda é longa, musculosa e achatada, o que facilita a deslocação nos rios. Além disso, as patas são curtas com dedos espalmados unidos por membranas.\r\n<br><br>\r\n<strong>Dieta:</strong> As Ariranhas possuem uma dieta carnívora, e os peixes são os animais preferidos delas. Na maioria das vezes, as principais espécies consumidas são as piranhas, a traíra e também alguns caracídeos. Para se alimentar, elas colocam as suas cabeças para fora da água, e nadam de forma pitoresca para trás. Além disso, elas também não desperdiçam um “almoço” formado por crustáceos, cobras, moluscos, ovos e até mesmo pássaros.', 1),
(25, 'Lobo-guará', 'uploads\\lobo-guara.jpg', '', '', 0),
(26, 'Anta-brasileira', 'uploads\\anta-brasileira.jpg', '', '', 0),
(27, 'Tamanduá-bandeira', 'uploads\\tamanduá-bandeira.jpg', 'Caça e perda de habitat', '<strong>Quem é?:</strong> O Tamanduá-bandeira é um mamífero nativo da América. Ele recebe esse nome uma vez que sua cauda tem forma de uma bandeira. Em alguns locais do Brasil eles são conhecidos pelos nomes: tamanduá-açu, tamanduá-cavalo, papa-formigas-gigante, urso-formigueiro-gigante, iurumi, jurumim. Pertence à classe de mamíferos (Mammalia), ordem Xenarthra e família dos Myrmecophagidae, sendo seu nome científico Myrmecophaga tridactyla.\r\n<br><br>\r\n<strong>Ameaças:</strong> Infelizmente, em alguns locais ele já foi extinto e no Brasil é um dos animais na lista de risco de extinção. O desmatamento, a caça e a fragmentação do habitat são as principais ameaças à sobrevivência do Tamanduá-bandeira.\r\n<br><br>\r\n<strong>Habitat:</strong> O tamanduá-bandeira vive em campos, áreas abertas e florestas tropicais. Ele é encontrado em todos os biomas brasileiros: Amazônia, Caatinga, Mata Atlântica, Pantanal, Cerrado e Pampa. Além do Brasil, ele é encontrado em outras partes do continente americano (América do Sul e Central).\r\n<br><br>\r\n<strong>Hábitos:</strong> Os tamanduás-bandeiras são animais diurnos ou noturnos. Essa característica varia de acordo com a região que habitam, segundo a temperatura e o índice pluviométrico (chuvas). São animais solitários quando atingem a idade adulta. Não são ágeis, nem agressivos, no entanto, se se sentem ameaçados eles sentam sobre as patas traseiras e atacam com suas imensas garras. Não são animais territorialistas e por isso podem caminhar durante todo o dia em busca de abrigo e alimento. Além disso, eles conseguem nadar. Embora sejam grandes e pesados, suas imensas garras lhes permitem subir em árvores. Esse comportamento de defesa é fundamental para se protegerem de alguns predadores.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Tamanduá-bandeira possui pelos muito longos pelo corpo, além de um imensa cauda peluda e focinho fino e cilíndrico. Eles são quadrúpedes (possuem quatro patas) e se locomovem de maneira vagarosa. São geralmente cinzentos ou marrons e possuem uma faixa preta e branca que se estende diagonalmente pelo corpo todo. Apresenta enormes, forte e curvadas garras que o auxiliam na defesa. Com elas também eles conseguem atingir formigueiros ou habitações de insetos para se alimentarem. Ainda que a visão deles não seja muito apurada, eles compensam com o desenvolvido olfato que possuem. Ainda que seja um mamífero, ele não possui dentes. Sua boca é pequena, no entanto, sua língua é muito grande e possui uma espécie de saliva viscosa e pegajosa que “cola” seus alimentos.\r\n<br><br>\r\n<strong>Dieta:</strong> O Tamanduá-Bandeira se alimenta principalmente de pequenos insetos, por exemplo, formigas, cupins, larvas, centopeias, vermes.', 1),
(28, 'Queixada', 'uploads\\queixada.jpg', 'Caça e destruição do habitat', '<strong>Quem é?:</strong> O \"Queixada\" é um mamífero artiodáctilo da família dos taiaçuídeos e gênero Tayassu. Eles são conhecidos por vários nomes, como queixada-ruiva, queixo-ruivo, canela-ruiva, sabucu, tacuité, taiaçu, tajaçu, tanhaçu, tanhocati, taguicati, tiririca, porco-do-mato, pecari.\r\n<br><br>\r\n<strong>Ameaças:</strong> A destruição do habitat, devido ao desmatamento e à expansão agrícola, é uma das principais ameaças. Além disso, a caça ilegal também representa um problema, pois a carne da Queixada é considerada uma iguaria em algumas regiões.\r\n<br><br>\r\n<strong>Habitat:</strong> As queixadas habitam as florestas tropicais que se estendem do sul do México ao Paraguai, sendo ainda abundante nas florestas do Amazonas e nas florestas litorâneas do Brasil até o sul do país.\r\n<br><br>\r\n<strong>Hábitos:</strong> As queixadas são animais territoriais, e assim como todo animal territorial eles o defendem, ao contrário de outros porcos selvagens que marcam o território por meio das glândulas de cheiro em diversos locais onde defecam. As queixadas são consideradas animais nômades e portanto assim não apresentam e não exibem comportamentos iguais.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O queixada é um mamífero de porte médio, com um corpo robusto e pernas curtas. Possui uma pelagem densa e áspera, que varia em tons de marrom e preto. Sua cabeça é grande e possui um focinho alongado, com presas proeminentes. Os machos são maiores que as fêmeas, podendo chegar a medir até 1,2 metros de comprimento e pesar cerca de 30 a 40 quilos.\r\n<br><br>\r\n<strong>Dieta:</strong> As queixadas são animais onívoros e se alimentam de frutos, sementes, raízes, larvas de insetos e minhocas. Por se alimentarem basicamente de frutas, as queixadas também são conhecidas pela dispersão de sementes no meio em que vivem, através das fezes.', 1),
(29, 'Pato-mergulhão', 'uploads\\pato-mergulhão.jpg', 'Perda de habitat e poluição', '<strong>Quem é?:</strong> O pato-mergulhão (Mergus octosetaceus) é uma ave endêmica do Brasil da família Anatidae e do gênero Mergus. É uma das 10 aves aquáticas mais raras, emblemáticas e ameaçadas de extinção do mundo.\r\n<br><br>\r\n<strong>Ameaças:</strong> O pato-mergulhão é uma das aves aquáticas mais ameaçadas do mundo. Entre as maiores ameaças a sua sobrevivência estão a destruição de matas ciliares e a degradação das margens e leitos de cursos d\'água, uso de agrotóxicos em pastagens e lavouras, mineração, barragens para geração de energia e outros fins e atividades esportivas ou turísticas mal planejadas.\r\n<br><br>\r\n<strong>Habitat:</strong> O pato-mergulhão habita rios de águas límpidas, com corredeiras e envoltos por vegetação ciliar em áreas de cerrado e floresta subtropical, sendo o único representante dos Mergini (Anseriformes) no Hemisfério Sul. A espécie se distribui no Brasil, Argentina e Paraguai.\r\n<br><br>\r\n<strong>Hábitos:</strong> O pato-mergulhão frequenta rios rápidos de montanha, mergulha muito e vive em rios ou ribeirões com corredeiras, em regiões serranas. Principalmente em rios com fundo areno/rochoso e onde a coluna d\'água é rasa, possibilitando a visibilidade do fundo indispensável para sua alimentação e caça de presas. O pato-mergulhão é monogâmico e forma pares para toda a vida. É uma espécie residente que não abandona os cursos de água onde estabeleceu o seu território. Eles não se movem ou querem se mover uma vez que seus habitats tenham desaparecido.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O pato-mergulhão é um pato escuro e esguio com um capuz verde-escuro brilhante com uma longa crista, que geralmente é mais curta e com aparência mais desgastada nas fêmeas. As partes superiores são cinza escuro, enquanto o peito é cinza claro, ficando mais claro em direção ao ventre esbranquiçado, e uma mancha branca nas asas é particularmente perceptível em vôo. Tem um bico preto longo e fino com pés e pernas vermelhos. Embora as fêmeas sejam menores com bico e crista mais curtos, ambos os sexos são semelhantes em cores. Os patos esguios variam em tamanho de 49 a 56 centímetros quando adultos.\r\n<br><br>\r\n<strong>Dieta:</strong> O pato-mergulhão se alimenta de peixes de até 12 centímetros e necessita de águas limpas e transparentes, principalmente dos rios e córregos cercados por matas ciliares, com cachoeiras e piscinas de diferentes tamanhos e profundidades. É considerado um \"bioindicador\" ambiental: o bem-estar e a reprodução da espécie significam que o habitat e a qualidade água estão em equilíbrio. Quando o ambiente está poluído ou degradado, o pato-mergulhão desaparece.', 1),
(30, 'Rolinha-do-planalto', 'uploads\\rolinha-do-planalto.jpg', 'Perda de habitat', '<strong>Quem é?:</strong> A Rolinha-do-planalto (Columbina cyanopis) é uma espécie de ave da família Columbidae, também conhecida como rolinha de janeiro, rolinha-brasileira ou pombinha-olho-azul. É endêmica da região do Cerrado no Brasil.\r\n<br><br>\r\n<strong>Ameaças:</strong> A Rolinha-do-planalto é considerada criticamente ameaçada pela IUCN devido à perda de habitat. Não era registrada na natureza desde 1941 e era conhecida por apenas cinco espécimes coletados naquele ano e depositados em museus.\r\n<br><br>\r\n<strong>Habitat:</strong> Seu habitat natural são florestas subtropicais ou tropicais secas com planície de pastagem. A Rolinha-do-planalto habita savana aberta e pastagens no cerrado brasileiro.\r\n<br><br>\r\n<strong>Hábitos:</strong> A Rolinha-do-planalto foi redescoberta em 2015, contabilizando, na ocasião, aproximadamente 12 espécimes. A ave foi avistada quase por acaso pelo ornitólogo Rafael Bessa, durante uma expedição pelo Cerrado.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> A Rolinha-do-planalto tem 15,5 cm (6,1 pol.) de comprimento. A cabeça, o pescoço, as coberturas das asas, as coberturas da cauda superior e o peito do macho são vermelho arroxeado. A parte inferior do peito, barriga, flancos, ombros e costas são mais marrons. Sua cloaca e abrigos infracaudais são brancos. A asa fechada mostra marrom escuro e castanho com manchas azuis iridescentes. As penas centrais da cauda são ruivas e as externas mais escuras. Seu olho é azul cercado por pele cinza nua.\r\n<br><br>\r\n<strong>Dieta:</strong> Se alimenta de sementes, como os outros membros de seu gênero.', 1),
(31, 'Chorozinho-de-boné', 'uploads\\chorozinho-de-boné.jpg', 'Perda de habitat', '<strong>Quem é?:</strong> O Chorozinho-de-boné é uma espécie de ave passeriforme da família Thamnophilidae. É um pássaro com boné que rasteja pelo bosque.\r\n<br><br>\r\n<strong>Ameaças:</strong> O Chorozinho-de-boné está ameaçado de extinção devido à destruição e degradação de seu ambiente, em razão da ocupação imobiliária e agropecuária.\r\n<br><br>\r\n<strong>Habitat:</strong> Esta espécie é endêmica do Brasil e seus habitats naturais são: florestas secas tropicais ou subtropicais, florestas subtropicais ou tropicais úmidas de baixa altitude e matagal úmido tropical ou subtropical. Ele vive em áreas de mata atlântica e restingas arbóreas do litoral do estado da Bahia.\r\n<br><br>\r\n<strong>Hábitos:</strong> O Chorozinho-de-boné tem hábitos alimentares específicos. Ele habita o estrato médio e dossel de florestas costeiras (restinga), onde são vistos só ou acompanhando bandos mistos.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Chorozinho-de-boné mede 11,5 cm de comprimento e tem a cauda relativamente curta.\r\n<br><br>\r\n<strong>Dieta:</strong> É provável que sua dieta seja composta por uma variedade de insetos e outros pequenos invertebrados.', 1),
(32, 'Peixe-rei', 'uploads\\peixe-rei.jpg', 'Pesca predatória e perda de habitat', '<strong>Quem é?:</strong> O Peixe-rei (Odontesthes bonariensis) é uma espécie de peixe relativamente abundante em rios, lagoas e região costeira da América do Sul, desde o sul do Brasil até a Argentina. Ele pertence à família Atherinopsidae e ao gênero Odontesthes.\r\n<br><br>\r\n<strong>Ameaças:</strong> O Peixe-rei está ameaçado pela pesca predatória, degradação do habitat e barragens que impedem sua migração nas áreas de desova na cabeceira do rio.\r\n<br><br>\r\n<strong>Habitat:</strong> O Peixe-rei é uma espécie abundante em rios, lagoas e região costeira da América do Sul, incluindo Brasil e Argentina. Ele também pode ser encontrado em pesqueiros, lugares especialmente construídos para a prática da pesca.\r\n<br><br>\r\n<strong>Hábitos:</strong> Os cardumes desta espécie se concentram em volta da isca, tornando a pesca relativamente fácil. Eles se juntam e abocanham a isca.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> Em termos de estrutura corporal, os peixes em geral possuem um corpo hidrodinâmico, achatado lateralmente e alongado, o que favorece seu deslocamento na água. Eles também possuem nadadeiras, que são estruturas de locomoção. Dependendo da localização, essas podem ser peitorais, ventrais, dorsais, caudais e anais.\r\n<br><br>\r\n<strong>Dieta:</strong> O Peixe-rei tem uma dieta diversificada, sendo considerado uma espécie generalista e oportunista. Ele se alimenta de uma grande variedade de invertebrados, principalmente bentônicos.', 1),
(33, 'Cavalo-marinho', 'uploads\\cavalo-marinho.jpg', 'Pesca predatória e perda de habitat', '<strong>Quem é?:</strong> O cavalo-marinho é um pequeno peixe ósseo que apresenta uma cabeça alongada, semelhante à de um cavalo. Em geral, os cavalos-marinhos têm pouco mais de 15 cm. Eles pertencem à família Syngnathidae e, no Brasil, são encontradas duas espécies: Hippocampus reidi e Hippocampus erectus.\r\n<br><br>\r\n<strong>Ameaças:</strong> Atualmente, o cavalo-marinho está ameaçado de extinção devido à pesca predatória e à degradação de seu habitat. Eles costumam ser comercializados vivos para uso em aquários ou secos para fins decorativos. Um estudo global sobre o status de conservação desses animais revela que 14 entre 42 espécies mapeadas do Hippocampus (nome científico do peixe) estão ameaçadas de extinção.\r\n<br><br>\r\n<strong>Habitat:</strong> Os cavalos-marinhos são normalmente encontrados em águas rasas, em regiões temperadas e tropicais. Seus habitats favoritos são recifes de corais, gramas marinhas e manguezais.\r\n<br><br>\r\n<strong>Hábitos:</strong> Os cavalos-marinhos possuem pequenas barbatanas, o que não permite nadar contra a correnteza. Assim, eles preferem ambientes de águas tranquilas e rasas. Eles também podem mudar de cor e se camuflar, o que ajuda na defesa contra seus predadores. Além disso, eles têm dois olhos que podem se mover de forma independente um do outro.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O cavalo-marinho tem o corpo completamente recoberto por anéis ósseos articulados que lhe conferem proteção mecânica contra predadores. A cauda desses animais é longa e preênsil, o que permite que eles se agarrem às plantas submarinas enquanto se alimentam.\r\n<br><br>\r\n<strong>Dieta:</strong> Os cavalos-marinhos são carnívoros e se alimentam de pequenos crustáceos, moluscos, vermes e plâncton. Eles não têm estômago, então a comida que comem passa rapidamente por seus corpos e eles precisam comer com frequência.', 1),
(34, 'Peixe-boi-da-Amazônia', 'uploads\\peixe-boi.jpg', 'Caça, poluição e perda de habitat', '<strong>Quem é?:</strong> O Peixe-boi-da-Amazônia, também conhecido como Trichechus inunguis, é a menor espécie de peixe-boi do mundo. Ele é um mamífero herbívoro que vive em rios e lagos da bacia Amazônica. O animal pode chegar a 3 metros de comprimento e pesar até 450 kg. Sua coloração varia de cinza à preto, com uma mancha específica de cor branca ou rosada na barriga que pode ser comparada à uma impressão digital.\r\n<br><br>\r\n<strong>Ameaças:</strong> O Peixe-boi-da-Amazônia é uma espécie vulnerável, com tendência populacional declinante. A caça para alimentação, a perda de habitat, a poluição e a captura acidental em redes de pesca são as principais ameaças à sobrevivência da espécie. Entre 1935 e 1954, entre 80 mil e 140 mil peixes-bois-da-amazônia foram mortos por sua carne, gordura e pele. Embora essa prática tenha se tornado mais rara, a espécie ainda sofre com a caça ilegal.\r\n<br><br>\r\n<strong>Habitat:</strong> O Peixe-boi-da-Amazônia habita exclusivamente rios e lagos de água doce na bacia Amazônica, sendo endêmico dessa região. Ele não é encontrado acima de regiões com corredeiras. Na cheia, prefere várzeas e áreas alagadas, sempre com águas superiores a 23ºC. Na seca, migra para lagos e canais profundos.\r\n<br><br>\r\n<strong>Hábitos:</strong> Ao longo do ano, o comportamento do Peixe-boi-da-Amazônia varia conforme as estações de cheia e seca. Na cheia, prefere várzeas e áreas alagadas, sempre com águas superiores a 23ºC. Na seca, migra para lagos e canais profundos. Não há consenso sobre se esse movimento está relacionado apenas com a busca por alimentos, mas fato é que precisam consumir 8% do seu peso em plantas aquáticas e semiaquáticas todo dia: 50 espécies diferentes já foram identificadas no cardápio. Até onde se sabe, a espécie é solitária na maior parte do tempo. Eles já foram avistados em grupos, mas em geral o máximo observado é uma mãe acompanhada do filhote. A gestação dura 12 meses. Normalmente, apenas um pequeno peixe-boi nasce. Ele mama durante dois anos e as glândulas mamárias ficam localizadas nas axilas do animal.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Peixe-boi-da-Amazônia tem uma estrutura corporal adaptada para a vida aquática. Ele tem uma cauda comprida e arredondada e, ao contrário de outros peixes-bois, não tem unhas na ponta das nadadeiras. Sua coloração varia de cinza à preto, com uma mancha específica de cor branca ou rosada na barriga. Possui um couro extremamente grosso e resistente.\r\n<br><br>\r\n<strong>Dieta:</strong> O Peixe-boi-da-Amazônia é um mamífero herbívoro que se alimenta de plantas aquáticas e semiaquáticas. Ele precisa consumir 8% do seu peso em plantas todo dia: 50 espécies diferentes já foram identificadas no cardápio.', 1);
INSERT INTO `animais` (`id`, `nome`, `foto`, `ameaca`, `info`, `situacao`) VALUES
(35, 'Cancão-da-campina', 'uploads\\cancão-da-campina.jpg', 'Caça e perda de habitat', '<strong>Quem é?:</strong> O Cancão-da-campina (Cyanocorax hafferi) é uma espécie de ave passeriforme da família Corvidae. É conhecido popularmente como cancão-da-campina, canção da campina ou gralha-da-campina.\r\n<br><br>\r\n<strong>Ameaças:</strong> A espécie está criticamente ameaçada de extinção devido ao desmatamento, incêndios, caça ilegal e urbanização. Seu habitat está em perigo e podemos perder a espécie antes de ter tido tempo de estudá-la a fundo.\r\n<br><br>\r\n<strong>Habitat:</strong> O Cancão-da-campina é endêmico da Amazônia brasileira, vive apenas na beira de campinas naturais situadas em meio à floresta existente entre os rios Madeira e Purus, interflúvio no estado do Amazonas.\r\n<br><br>\r\n<strong>Hábitos:</strong> É uma ave inteligente, muito curiosa e barulhenta, com estratégias de alimentação diversificadas.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> Mede cerca de 35 centímetros de comprimento. Possui uma crista frontal rígida que cobre as narinas, tamanho global e plumagem semelhante a outros membros do gênero. É bastante parecida com a Gralha-de-nuca-azul, da qual difere por ser de cor azul celeste pálido, enquanto que a gralha-de-nuca-azul tem como cores predominantes azul escuro nas partes superiores e azul claro nas partes inferiores.\r\n<br><br>\r\n<strong>Dieta:</strong> Podem incluir sementes, frutas, insetos e pequenos invertebrados.', 1),
(36, 'Sabiá-castanho', 'uploads\\sabiá-castanho.jpg', 'Perda de habitat', '<strong>Quem é?:</strong> O Sabiá-castanho (Cichlopsis leucogenys) é uma espécie de ave passeriforme da família Turdidae, que pode ser encontrada na floresta de montanhas com população disjunta na América do Sul. Esta espécie ocorre em uma grande região, superior a 20.000 km de área.\r\n<br><br>\r\n<strong>Ameaças:</strong> A espécie está em declínio devido à perda de habitat. No Brasil, em 2005, foi classificado como em perigo na Lista de Espécies da Fauna Ameaçadas do Espírito Santo; em 2010, como criticamente em perigo na Lista de Espécies Ameaçadas de Extinção da Fauna do Estado de Minas Gerais; em 2014, como em perigo na Portaria MMA N.º 444 de 17 de dezembro de 2014; em 2017, como em perigo na Lista Oficial das Espécies da Fauna Ameaçadas de Extinção do Estado da Bahia; e em 2018, como em perigo no Livro Vermelho da Fauna Brasileira Ameaçada de Extinção do Instituto Chico Mendes de Conservação da Biodiversidade (ICMBio).\r\n<br><br>\r\n<strong>Habitat:</strong> O Sabiá-castanho pode ser encontrado no Brasil, Colômbia, Equador, Guiana, Peru, Suriname e Venezuela. Habita florestas subtropicais ou tropicais úmidas de baixa altitude e regiões subtropicais ou tropicais húmidas de alta altitude, principalmente a 800 metros acima do nível do mar e ainda mais alto nos tepuis. A espécie habita as florestas primárias ou em avançado estado de regeneração, especialmente nas montanhas (acima de 700 m de altitude).\r\n<br><br>\r\n<strong>Hábitos:</strong> Como é uma ave discreta, pode passar despercebida dos observadores menos experientes, que podem até confundi-la com a fêmea do sabiá-una. Na maioria das vezes, é encontrado sozinho ou em pares. Canta no alto das árvores, sempre no meio das folhagens.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Sabiá-castanho mede entre 20 e 21 centímetros de comprimento e pesa entre 45 e 61 gramas, com corpo franzino e pés pequenos. Esta ave apresenta a coloração da plumagem uniformemente marrom acastanhada na parte superior. Com relação a garganta e peito também são castanhos, sendo que a garganta apresenta uma coloração ocrácea que inicia em uma área malar mais escura.\r\n<br><br>\r\n<strong>Dieta:</strong> Principalmente frugívora, e inclui alguns invertebrados.', 1),
(37, 'Tartaruga-Cabeçuda', 'uploads\\tartaruga-cabeçuda.jpg', 'Captura dos ovos e pesca', '<strong>Quem é?:</strong> A Tartaruga-Cabeçuda, também conhecida como tartaruga-meio-pente, tartaruga-amarela, tartaruga-mestiça, ou pelo seu nome científico Caretta caretta, é uma espécie marinha de tartaruga que vive nos oceanos de regiões tropicais e subtropicais. Ela é uma das maiores tartarugas marinhas, podendo pesar até 200 kg. Seu nome popular faz referência ao tamanho de sua cabeça, considerada grande em relação a outras espécies de tartarugas marinhas.\r\n<br><br>\r\n<strong>Ameaças:</strong> A Tartaruga-Cabeçuda está ameaçada de extinção. As principais ameaças são a captura dos ovos para consumo humano e acidentes causados pela pesca industrial. Além disso, a espécie é capturada por acidente por barcos de pesca industrial em todo o litoral brasileiro. A tartaruga-cabeçuda é vista como uma espécie em perigo de extinção pela União Internacional para a Conservação da Natureza. Dentre as causas, vale falar sobre as redes de arraste que causam o afogamento dos indivíduos.\r\n<br><br>\r\n<strong>Habitat:</strong> A Tartaruga-Cabeçuda vive em alto mar nos oceanos Atlântico, Índico, Pacífico e também no mar Mediterrâneo. Ela ocorre nos mares tropicais, subtropicais e em águas temperadas⁷.\r\n<br><br>\r\n<strong>Hábitos:</strong> Embora a tartaruga cabeçuda possa se mover rapidamente nas águas marinhas, na terra seu movimento é lento. Os machos raramente saem da água, enquanto as fêmeas o fazem exclusivamente para nidificar e pôr ovos. Esta espécie é um mergulhador de profundidade e pode fazê-lo por até 20 minutos.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> A Tartaruga-Cabeçuda tem uma cabeça enorme e uma mandíbula muito forte e poderosa. Sua carapaça possui cinco placas laterais, sendo que estas são justapostas, sua coloração é marrom-amarelada e seu ventre amarelo claro; sua cabeça possui dois pares de placas ou escudos pré-frontais e três pares pós-orbitais.\r\n<br><br>\r\n<strong>Dieta:</strong> Quando jovens, as Tartarugas-Cabeçudas comem esponjas, águas-vivas, algas, gastrópodes e crustáceos. Já adultas, tendem a uma dieta mais carnívora, que também inclui outros moluscos e até peixes.', 1),
(38, 'Macaco-prego-dourado', 'uploads\\macaco-prego-dourado.jpg', 'Desmatamento', '<strong>Quem é?:</strong> O Macaco-prego-dourado, também conhecido como Macaco-prego-galego, é uma espécie de macaco-prego, um macaco do Novo Mundo da família Cebidae e gênero Sapajus. Sua identidade e linhagem eram desconhecidas até 2005.\r\n<br><br>\r\n<strong>Ameaças:</strong> É classificado como \"criticamente em perigo\" pela IUCN. Vive em área com longa história de colonização pelos europeus e de desmatamento e todo o habitat foi reduzido a pequenos fragmentos cercados por plantações de cana-de-açúcar e pastagens, o que representa menos 5% da cobertura original da Mata Atlântica.\r\n<br><br>\r\n<strong>Habitat:</strong> Ocorre na costa nordeste do Brasil, do sul do Rio Grande do Norte até o nordeste de Pernambuco. Sua distribuição se estende pelo interior até a Caatinga, na Serra do Estreito. Entretanto, habita principalmente os pequenos fragmentos de floresta secundária da Mata Atlântica, mangues e até canaviais.\r\n<br><br>\r\n<strong>Hábitos:</strong> Os grupos possuem entre 2 e 32 indivíduos, e vivem em sociedades de fissão-fusão. São animais onívoros de hábitos diurnos. O deslocamento destes animais consiste em utilizar as quatro patas, mas podem ser vistos andando sustentados apenas nas patas traseiras. São animais arborícolas que utilizam a cauda semi-preênsil para se deslocar entre os galhos. Descem ao solo apenas em épocas de alimento escasso.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> Possui entre 36,8 e 40 cm de comprimento, com a cauda tendo até 42 cm. Os machos pesam entre 2,9 e 3 kg, e as fêmeas entre 1,8 e 2,5 kg. A pelagem é uniformemente dourada, e as partes inferiores dos membros são mais escuras. Não possui topete aparente. Possui longos pelos no pescoço. As mãos e pés são pretos. A face é rosada e os olhos são marrons.\r\n<br><br>\r\n<strong>Dieta:</strong> Se alimentam de frutos, folhas, insetos e pequenos vertebrados. Podem ser vistos comendo pequenos invertebrados como lagartos e caranguejos e outros mamíferos. Além disso, possuem uma adaptação na alimentação para ingestão de substâncias rígidas como nozes e demais sementes.', 1),
(39, 'Pica-pau-de-cara-canela', 'uploads\\pica-pau-cara-de-canela.jpg', 'Caça e desmatamento de seu habitat', '<strong>Quem é?:</strong> O Pica-pau-de-cara-canela é uma espécie de ave pertencente à família dos picídeos. Ele também é conhecido como pica-pau-de-cara-amarela.\r\n<br><br>\r\n<strong>Ameaças:</strong> Esta espécie está ameaçada de extinção pela caça e desmatamento de seu habitat.\r\n<br><br>\r\n<strong>Habitat:</strong> A distribuição da espécie abrange os três tipos florestais da Mata Atlântica meridional: Floresta Ombrófila Densa, Floresta Ombrófila Mista e Floresta Estacional Semidecidual. Na Argentina e no Paraguai foi encontrada em florestas primárias e secundárias, plantações de árvores como araucária, pinheiro e até mesmo em grandes jardins com árvores nativas.\r\n<br><br>\r\n<strong>Hábitos:</strong> A espécie utiliza cavidades para passar a noite. Os hábitos reprodutivos ainda não são bem conhecidos. Sabe-se que constrói cavidades para nidificar.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> O Pica-pau-de-cara-canela mede cerca de 29 centímetros de comprimento, possui a cabeça e topete vermelhos, face e garganta creme-claras ou cor-de-canela, região auricular vermiculada; macho com faixa malar vermelha.\r\n<br><br>\r\n<strong>Dieta:</strong> Sua alimentação é constituída basicamente de insetos, os quais captura quase sempre dentro da floresta.', 1),
(40, 'Uruçu-preto', 'uploads\\uruçu-preto.jpg', 'Destruição do habitat', '<strong>Quem é?:</strong> A Uruçu-preto, também conhecida como uruçu-capixaba, é uma espécie de abelha eusocial sem ferrão, pertencente à ordem dos himenópteros e à família dos apídeos (Apidae). As operárias de uruçu-preto se distinguem de outras espécies do gênero por sua cabeça e tórax predominantemente castanho-escuros, mesonoto negro, liso e brilhante com pilosidade fusca, faixas pré-marginais dos tergos metassomáticos quase nulas e desenhos amarelos no clípeo e paraoculares inferiores.\r\n<br><br>\r\n<strong>Ameaças:</strong> Destruição do habitat por impactos agrícolas. No Brasil, foi incluída desde 2003 na lista de espécies ameaçadas produzidas pelo Ministério do Meio Ambiente. Em 2005, foi classificada como vulnerável na Lista de Espécies da Fauna Ameaçadas do Espírito Santo e, em 2018, foi listada como em perigo no Livro Vermelho da Fauna Brasileira Ameaçada de Extinção do Instituto Chico Mendes de Conservação da Biodiversidade (ICMbio).\r\n<br><br>\r\n<strong>Habitat:</strong> O uruçu-preto se restringe às formações florestais situadas na região serrana do estado do Espírito Santo em altitudes que variam de 800 a 1 200 metros. Geralmente, as Abelhas Uruçu são encontradas nas regiões mais quentes do país como Norte, Nordeste Centro-Oeste e até Sudeste.\r\n<br><br>\r\n<strong>Hábitos:</strong> Apesar da sua importância ecológica como agente polinizador, poucos estudos examinaram a ecologia e a biologia desta abelha. Ela é responsável por polinizar orquídeas dentro de sua distribuição.\r\n<br><br>\r\n<strong>Estrutura Corporal:</strong> A Uruçu possui corpo robusto, face estreita, tórax preto no dorso, com pelos densos amarelo-dourados. O abdômen é escuro, com cinco listras claras. O comprimento das operárias é de 10 a 12 mm.\r\n<br><br>\r\n<strong>Dieta:</strong> Se alimenta de néctar e pólen de flores. Além disso, ela é conhecida por polinizar orquídeas.', 1),
(41, 'Pardal Albino', 'uploads\\pardal.jpg', '', '', 0),
(42, 'Perereca Fluorescente', 'uploads\\pererecafluorescente.jpg', '', '', 0),
(43, 'Caranguejeira-rosa-salmão-brasileira', 'uploads\\caranguejeira-rosa-salmão-brasileira.jpg', '', '', 0),
(44, 'Fila-brasileiro', 'uploads\\filabrasileiro.jpg', '', '', 0),
(45, 'Arara-vermelha', 'uploads\\arara-vermelha.jpg', '', '', 0),
(46, 'Coró-coró', 'uploads\\coró-coró.jpg', '', '', 0),
(47, 'Garça-real', 'uploads\\garça-real.jpg', '', '', 0),
(48, 'Jacaretinga', 'uploads\\jacaretinga.jpg', '', '', 0),
(49, 'Jararaca Cinza', 'uploads\\jararacacinza.jpg', '', '', 0),
(50, 'Pavãozinho-do-pará', 'uploads\\pavãozinho-do-pará.jpg', '', '', 0),
(51, 'Onça-parda', 'uploads\\onça-parda.jpg', '', '', 0),
(52, 'Surucucu', 'uploads\\surucucu.jpg', '', '', 0),
(53, 'Bicho-preguiça', 'uploads\\bicho-preguiça.jpg', '', '', 0),
(54, 'Ema', 'uploads\\ema.jpg', '', '', 0),
(55, 'Paca', 'uploads\\paca.jpg', '', '', 0),
(56, 'Seriema', 'uploads\\seriema.jpg', '', '', 0),
(57, 'Tuiuiú', 'uploads\\tuiuiu.jpg', '', '', 0),
(58, 'Capivara', 'uploads\\capivara.jpg', '', '', 0),
(59, 'Gambá-amazônico', 'uploads\\gamba.jpg', '', '', 0),
(60, 'Suindara', 'uploads\\suindara.jpg', '', '', 0),
(61, 'Gato-maracajá', 'uploads\\gato-maracaja.jpg', '', '', 0),
(62, 'Periquito-da-Caatinga', 'uploads\\periquito-da-caatinga.jpg', '', '', 0),
(63, 'Baleia Jubarte', 'uploads\\baleia-jubarte.jpg', '', '', 0),
(64, 'Baleia-franca austral', 'uploads\\baleia-franca-austral.jpg', '', '', 0),
(65, 'Caititu', 'uploads\\caititu.jpg', '', '', 0),
(66, 'Cuíca-cauda-de-rato', 'uploads\\cuíca-cauda-de-rato.jpg', '', '', 0),
(67, 'Morcego-vampiro', 'uploads\\morcego-vampiro.jpg', '', '', 0),
(68, 'Tubarão-tigre', 'uploads\\tubarão-tigre.jpg', '', '', 0),
(69, 'Tubarão azul', 'uploads\\tubarão-azul.jpg', '', '', 0),
(70, 'Lagartixa-doméstica-tropical', 'uploads\\lagartixa-doméstica-tropical.jpg', '', '', 0),
(71, 'Iguana', 'uploads\\iguana.jpg', '', '', 0),
(72, 'Chororó-do-pantanal', 'uploads\\chororó-do-pantanal.jpg', '', '', 0),
(73, 'Garça', 'uploads\\garça.jpg', '', '', 0),
(74, 'Gavião-preto', 'uploads\\gavião-preto.jpg', '', '', 0),
(75, 'Piranha', 'uploads\\piranha.jpg', '', '', 0),
(76, 'Traíra', 'uploads\\traíra.jpg', '', '', 0),
(77, 'Bicho-pau', 'uploads\\bicho-pau.jpg', '', '', 0),
(78, 'Pica-pau-amarelo', 'uploads\\pica-pau-amarelo.jpg', '', '', 0),
(79, 'Jacu', 'uploads\\jacu.jpg', '', '', 0),
(80, 'Libélula', 'uploads\\libelula.jpg', '', '', 0),
(81, 'Urubu-rei', 'uploads\\urubu-rei.jpg', '', '', 0),
(82, 'Galo Índio Gigante', 'uploads\\galo-indio-gigante.jpg', '', '', 0),
(83, 'Bagre', 'uploads\\bagre.jpg', '', '', 0),
(84, 'Tapiti', 'uploads\\tapiti.jpg', '', '', 0),
(85, 'Macaco-da-noite', 'uploads\\macaco.jpg', '', '', 0),
(86, 'Sapo cururu', 'uploads\\sapocururu.jpg', '', '', 0),
(87, 'Gafanhoto', 'uploads\\gafanhoto.jpg', '', '', 0),
(88, 'Borboleta-caixão-de-defunto', 'uploads\\borboleta-caixao-de-defunto.jpg', '', '', 0),
(89, 'Formiga-de-fogo', 'uploads\\formiga.jpg', '', '', 0),
(90, 'Varejeira Azul', 'uploads\\mosca.jpg', '', '', 0),
(91, 'Putrião', 'uploads\\putriao.jpg', '', '', 0);

-- --------------------------------------------------------

--
-- Table structure for table `score`
--

CREATE TABLE `score` (
  `id_user` int(11) DEFAULT NULL,
  `id` int(11) NOT NULL,
  `score` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `score`
--

INSERT INTO `score` (`id_user`, `id`, `score`) VALUES
(1, 71, 10),
(1, 72, 10),
(1, 73, 10),
(1, 74, 10),
(1, 75, 10),
(1, 76, 10),
(1, 77, 10),
(1, 78, 10);

-- --------------------------------------------------------

--
-- Table structure for table `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `nome` text NOT NULL,
  `dataNascimento` text NOT NULL,
  `email` text NOT NULL,
  `tipo` int(11) NOT NULL,
  `senha` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `usuarios`
--

INSERT INTO `usuarios` (`id`, `nome`, `dataNascimento`, `email`, `tipo`, `senha`) VALUES
(1, 'Admin', '01/01/2000', 'adm@adm.com', 5, '276f1e72d6164794306e9a11532eb82919063e715070a89cf1bf8c5e8e803ccf'),
(2, 'Comum', '01/01/2000', 'comum@comum.com', 1, '5a56f6debeffa3535aefcf66743b73c2512ef1b41755e8e9ef7bbefaa047d530');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `animais`
--
ALTER TABLE `animais`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `score`
--
ALTER TABLE `score`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id_user` (`id_user`);

--
-- Indexes for table `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `animais`
--
ALTER TABLE `animais`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=92;

--
-- AUTO_INCREMENT for table `score`
--
ALTER TABLE `score`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;

--
-- AUTO_INCREMENT for table `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `score`
--
ALTER TABLE `score`
  ADD CONSTRAINT `score_ibfk_1` FOREIGN KEY (`id_user`) REFERENCES `usuarios` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
